name: SnoLib
description: SnoFox core lib
version: ${version}
main: net.snofox.minecraft.snolib.SnoLib
author: SnoFox
website: https://www.snofox.net/
api-version: 1.13
depend: []
softdepend: []
